fix: #121 + #58 (#124)

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -11,15 +11,23 @@ fi
 
 PRUSA_SLICER_APP_LOCALE_ERROR="An error occured while setting up locale"
 PRUSA_SLICER_APP_FALLBACK_LOCALE=en_US.UTF-8
-USE_LOCALE_WORKAROUND=$( (/app/bin/prusa-slicer --help 2>&1 | grep "$PRUSA_SLICER_APP_LOCALE_ERROR") >/dev/null && echo true || echo false)
+USE_LOCALE_WORKAROUND=$( (/app/bin/prusa-slicer --help 2>&1 | grep "$PRUSA_SLICER_APP_LOCALE_ERROR") >/dev/null && echo true || echo false )
 
 echo "--------------------------------------------------------------------------"
 echo "Message: $(date +%T): Starting PrusaSlicer flatpak with entrypoint script"
 echo "--------------------------------------------------------------------------"
 
 if [ $USE_LOCALE_WORKAROUND = true ]; then
-    [ -n "$LANG" ] && export LC_ALL=$LANG || export LC_ALL=$PRUSA_SLICER_APP_FALLBACK_LOCALE
-    echo "Message: $(date +%T): WARN: Executing prusa-slicer with locale workaround $LC_ALL"
+    echo "WARN: detected locale error, trying to use fallback locale"
+    # Check if LANG is in locale -a output
+    LANG_PRESENT=$( (locale -a | grep -q "^$LANG$") && echo true || echo false )
+    if [ $LANG_PRESENT = true ]; then
+        export LC_ALL=$LANG
+        echo "WARN: $LANG is available, setting LC_ALL to $LC_ALL."
+    else
+        export LC_ALL=$PRUSA_SLICER_APP_FALLBACK_LOCALE
+        echo "WARN: $LANG is not available in locale -a. Setting LC_ALL to $LC_ALL."
+    fi
 fi
 
 [ $PRUSA_SLICER_DARK_THEME == true ] &&
