clean script

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -12,106 +12,75 @@ PRUSA_SLICER_APP_APPLY_THEME=/app/bin/get_window_ids.py
 PRUSA_SLICER_APP_LOCALE_ERROR="An error occured while setting up locale"
 PRUSA_SLICER_APP_FALLBACK_LOCALE=en_US.UTF-8
 
-app_is_running() {
+is_running() {
     (ps aux | grep "$PRUSA_SLICER_APP" | grep -v "grep") >/dev/null
     [ $? == 0 ] && echo true || echo false
 }
 
-app_pid() {
-    echo $(pgrep -f $PRUSA_SLICER_APP)
-}
-
-app_detected_locale_issue() {
+is_locale_issue() {
     (grep "$PRUSA_SLICER_APP_LOCALE_ERROR" $PRUSA_SLICER_APP_LOG) >/dev/null
     [ $? == 0 ] && echo true || echo false
 }
 
-app_wait() {
-    wait_begin=1
-    wait_until=$1
-    while [ $(app_is_running) == true ]; do
-        #echo -e " --------------------------------------------------------------------------------------"
-        #echo -e " ⚫  PrusaSlicer is starting : $(app_is_running)  $(expr $(($wait_until + 1)) - $wait_begin)"
-        #echo -e " --------------------------------------------------------------------------------------"
-        [ $wait_begin == $wait_until ] && break
+do_wait() {
+    s=1
+    u=$1
+    while [ $(is_running) == true ]; do
+        [ $s == $u ] && break
         sleep 1
-        wait_begin=$(($wait_begin + 1))
+        s=$(($s + 1))
     done
-    echo -e " --------------------------------------------------------------------------------------"
-    [ $(app_is_running) == true ] && echo -e " 🟢  PrusaSlicer is running, pid $(app_pid)" || echo -e " 🔴  PrusaSlicer stopped running!"
-    echo -e " --------------------------------------------------------------------------------------"
-    #[ $(app_is_running) == false ] && echo -e "\n-- $PRUSA_SLICER_APP_LOG -- >>>\n" && cat $PRUSA_SLICER_APP_LOG && echo -e "\n<<< --\n"
+    [ $(is_running) == false ] &&
+        (cat $PRUSA_SLICER_APP_LOG &) ||
+        (cat $PRUSA_SLICER_APP_LOG &)
 }
 
-apply_dark_window() {
+set_dark_variant() {
     while IFS= read -r window_id; do
         (xprop -f _GTK_THEME_VARIANT 8u -set _GTK_THEME_VARIANT "dark" -id "$window_id") &>>/dev/null
     done <<<$($PRUSA_SLICER_APP_APPLY_THEME)
 }
 
-app_start() {
+do_start() {
     source $PRUSA_SLICER_APP_ENV
-
-    RETRY_STEP=$1
-
-    [ $RETRY_STEP == 0 ] && echo -e " 🎲  PrusaSlicer, executed $PRUSA_SLICER_APP $PRUSA_SLICER_APP_ARGS"
-    [ $RETRY_STEP == 2 ] && echo -e " 🎲  PrusaSlicer, executed again with LC_ALL=$LC_ALL"
-    [ $RETRY_STEP == 3 ] && echo -e " 🎲  PrusaSlicer, executed with previous generated $PRUSA_SLICER_APP_ENV"
-
     (exec $PRUSA_SLICER_APP ${PRUSA_SLICER_APP_ARGS[@]} &) 2>$PRUSA_SLICER_APP_LOG 1>/dev/null
-    [ $PRUSA_SLICER_DARK_THEME == true ] && (apply_dark_window &)
+    [ $PRUSA_SLICER_DARK_THEME == true ] && (set_dark_variant &)
 }
 
-override_locale() {
+set_fallback() {
     [ -n "$LANG" ] && echo -e "export LC_ALL=$LANG" >>$PRUSA_SLICER_APP_ENV ||
         echo -e "export LC_ALL=$PRUSA_SLICER_APP_FALLBACK_LOCALE" >>$PRUSA_SLICER_APP_ENV
 }
 
-check() {
-    maximum_retrys=$1
-    while [ $maximum_retrys -le 3 ]; do
-        if [ $(app_is_running) == true ]; then
-            break
-        else
-            maximum_retrys=$(($maximum_retrys + 1))
+do_restart() {
+    if [ $(is_running) == false ]; then
+        [ $(is_locale_issue) ] && set_fallback
 
-            [ $(app_detected_locale_issue) ] && override_locale && echo -e " 🟠  PrusaSlicer: $PRUSA_SLICER_APP_LOCALE_ERROR!" && echo -e " --------------------------------------------------------------------------------------"
-            app_start $maximum_retrys
-            app_wait 5
-        fi
-    done
+        do_start
+        do_wait 5
+    fi
 }
 
-echo -e "\n"
-echo -e " PRUSA SLICER startup script for flatpak package on flathub.org"
-echo -e " --------------------------------------------------------------------------------------"
-echo -e " this startup script was written as a workaround and adresses some locale issues that "
-echo -e " prevented PrusaSlicer from starting up when working in a mixed locale enviroment."
-echo -e " Also some initial support for dark theme/variant was added.\n"
-echo -e " Disable dark theme/variant with --env=PRUSA_SLICER_DARK_THEME=false\n"
-echo -e " Links:\n  - https://github.com/flathub/com.prusa3d.PrusaSlicer/blob/beta/entrypoint"
-echo -e "  - https://github.com/flathub/com.prusa3d.PrusaSlicer/pull/33"
-echo -e " --------------------------------------------------------------------------------------\n"
+main() {
 
-RETRY=0
+    [ -f $PRUSA_SLICER_APP_ENV ] &&
+        [ -f $PRUSA_SLICER_APP_LOG ] && is_init=true || is_init=false
 
-if [ -f $PRUSA_SLICER_APP_ENV ] && [ -f $PRUSA_SLICER_APP_LOG ]; then
-    RETRY=3
-fi
+    [ $is_init == false ] &&
+        echo -e "# start of $PRUSA_SLICER_APP_ENV file" >$PRUSA_SLICER_APP_ENV
+    [ $is_init == false ] &&
+        echo -e "# start of $PRUSA_SLICER_APP_LOG file" >$PRUSA_SLICER_APP_LOG
+    [ $is_init == false ] && [ $PRUSA_SLICER_DARK_THEME == true ] &&
+        echo -e "export GTK_THEME='Adwaita:dark'" >>$PRUSA_SLICER_APP_ENV
 
-[ $RETRY == 0 ] && [ ! -f $PRUSA_SLICER_APP_ENV ] && echo -e "# start of $PRUSA_SLICER_APP_ENV file" >$PRUSA_SLICER_APP_ENV
-[ $RETRY == 0 ] && [ ! -f $PRUSA_SLICER_APP_LOG ] && echo -e "# start of $PRUSA_SLICER_APP_LOG file" >$PRUSA_SLICER_APP_LOG
-[ $RETRY == 0 ] && [ $PRUSA_SLICER_DARK_THEME == true ] && echo -e "export GTK_THEME='Adwaita:dark'" >>$PRUSA_SLICER_APP_ENV
+    [ ! -e $PRUSA_SLICER_APP_ENV ] &&
+        echo -e "❗ $PRUSA_SLICER_APP_ENV file not found!" && exit 1
+    [ ! -e $PRUSA_SLICER_APP_LOG ] &&
+        echo -e "❗ $PRUSA_SLICER_APP_LOG file not found!" && exit 1
 
-[ ! -e $PRUSA_SLICER_APP_ENV ] && echo -e "❗ $PRUSA_SLICER_APP_ENV file not found!" && exit 1
-[ ! -e $PRUSA_SLICER_APP_LOG ] && echo -e "❗ $PRUSA_SLICER_APP_LOG file not found!" && exit 1
+    do_start && do_wait 5
+    [ $(is_running) == false ] &&
+        do_restart
+}
 
-(
-    app_start $RETRY &
-    app_wait 5
-)
-
-if [ $(app_is_running) == false ]; then
-    RETRY=$(($RETRY + 1))
-    (check $RETRY)
-fi
+main
